Repository ros-simulation/gazebo_ros_pkgs, pull requests merged in 2020-12, with the labels that each got.

#1133 [noetic][planar_move_controller] add cmdTimeout param
  gazebo_plugins/include/gazebo_plugins/gazebo_ros_planar_move.h
  gazebo_plugins/src/gazebo_ros_planar_move.cpp
Labels: enhancement

#1205 ros2: Only subscribe to /gazebo/performance_metrics when necessary
  gazebo_ros/src/gazebo_ros_init.cpp
Labels: ros2

#1206 Update test worlds to use the correct element names for xyzOffset and rpyOffset
  gazebo_plugins/test/p3d_test/worlds/3_double_pendulums.world
  gazebo_plugins/test/p3d_test/worlds/3_single_pendulums.world
  gazebo_plugins/test/p3d_test/worlds/double_pendulum.world
  gazebo_plugins/test/p3d_test/worlds/single_pendulum.world
Labels: backwards compatible, bug
