Repository ros-simulation/gazebo_ros_pkgs, pull requests merged in 2020-11, with the labels that each got.

#1184 Fixed Parameterized testing
  gazebo_plugins/test/test_gazebo_ros_camera.cpp
  gazebo_plugins/test/test_gazebo_ros_camera_distortion.cpp
  gazebo_plugins/test/test_gazebo_ros_depth_camera.cpp
  gazebo_plugins/test/test_gazebo_ros_diff_drive.cpp
  gazebo_plugins/test/test_gazebo_ros_multi_camera.cpp
  gazebo_plugins/test/test_gazebo_ros_multicamera.cpp
  gazebo_ros/test/test_plugins.cpp
Labels: test

#1188 Fix sdf ros topic naming bug
  gazebo_plugins/src/gazebo_ros_force.cpp
Labels: bug

#1193 [foxy] Update repos file to use 'foxy' branch
  gazebo_ros_pkgs.repos
Labels: bug, ros2
