Repository ros-simulation/gazebo_ros_pkgs, pull requests merged in 2020-08, with the labels that each got.

#1146 [ROS 2] Added lockstep argument to gzserver
  gazebo_ros/launch/gzserver.launch.py
Labels: enhancement, ros2

#1144 [Noetic] Added directives if profiler is not installed
  gazebo_plugins/src/gazebo_ros_block_laser.cpp
  gazebo_plugins/src/gazebo_ros_bumper.cpp
  gazebo_plugins/src/gazebo_ros_camera.cpp
  gazebo_plugins/src/gazebo_ros_depth_camera.cpp
  gazebo_plugins/src/gazebo_ros_diff_drive.cpp
  gazebo_plugins/src/gazebo_ros_f3d.cpp
  gazebo_plugins/src/gazebo_ros_force.cpp
  gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
  gazebo_plugins/src/gazebo_ros_gpu_laser.cpp
  gazebo_plugins/src/gazebo_ros_hand_of_god.cpp
  gazebo_plugins/src/gazebo_ros_harness.cpp
  gazebo_plugins/src/gazebo_ros_imu.cpp
  gazebo_plugins/src/gazebo_ros_imu_sensor.cpp
  gazebo_plugins/src/gazebo_ros_joint_pose_trajectory.cpp
  gazebo_plugins/src/gazebo_ros_joint_state_publisher.cpp
  gazebo_plugins/src/gazebo_ros_laser.cpp
  gazebo_plugins/src/gazebo_ros_multicamera.cpp
  gazebo_plugins/src/gazebo_ros_openni_kinect.cpp
  gazebo_plugins/src/gazebo_ros_p3d.cpp
  gazebo_plugins/src/gazebo_ros_planar_move.cpp
  gazebo_plugins/src/gazebo_ros_projector.cpp
  gazebo_plugins/src/gazebo_ros_prosilica.cpp
  gazebo_plugins/src/gazebo_ros_range.cpp
  gazebo_plugins/src/gazebo_ros_skid_steer_drive.cpp
  gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
  gazebo_plugins/src/gazebo_ros_triggered_camera.cpp
  gazebo_plugins/src/gazebo_ros_triggered_multicamera.cpp
  gazebo_plugins/src/gazebo_ros_vacuum_gripper.cpp
  gazebo_plugins/src/gazebo_ros_video.cpp
Labels: enhancement

#1141 Added ignition common profiler to ros2
  .ros1_unported/gazebo_plugins/src/gazebo_ros_prosilica.cpp
  gazebo_plugins/CMakeLists.txt
  gazebo_plugins/include/gazebo_plugins/gazebo_ros_camera.hpp
  gazebo_plugins/src/gazebo_ros_ackermann_drive.cpp
  gazebo_plugins/src/gazebo_ros_bumper.cpp
  gazebo_plugins/src/gazebo_ros_camera.cpp
  gazebo_plugins/src/gazebo_ros_diff_drive.cpp
  gazebo_plugins/src/gazebo_ros_force.cpp
  gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
  gazebo_plugins/src/gazebo_ros_gps_sensor.cpp
  gazebo_plugins/src/gazebo_ros_hand_of_god.cpp
  gazebo_plugins/src/gazebo_ros_imu_sensor.cpp
  gazebo_plugins/src/gazebo_ros_joint_pose_trajectory.cpp
  gazebo_plugins/src/gazebo_ros_joint_state_publisher.cpp
  gazebo_plugins/src/gazebo_ros_p3d.cpp
  gazebo_plugins/src/gazebo_ros_planar_move.cpp
  gazebo_plugins/src/gazebo_ros_projector.cpp
  gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
  gazebo_plugins/src/gazebo_ros_vacuum_gripper.cpp
  gazebo_plugins/src/gazebo_ros_video.cpp
  gazebo_plugins/test/CMakeLists.txt
Labels: ros2

#1099 Port wheel slip plugin to ros2 (eloquent)
  gazebo_plugins/CMakeLists.txt
  gazebo_plugins/include/gazebo_plugins/gazebo_ros_wheel_slip.hpp
  gazebo_plugins/src/gazebo_ros_wheel_slip.cpp
  gazebo_plugins/worlds/gazebo_ros_wheel_slip_demo.world
Labels: ros2

#1035 [ros2] Enable the force system on launch files
  gazebo_ros/launch/gzserver.launch.py
  gazebo_ros/worlds/gazebo_ros_force_system_demo.world
Labels: backwards compatible, ros2
