Repository ros-simulation/gazebo_ros_pkgs, pull requests merged in 2020-07, with the labels that each got.

#713 [Add] gazebo_plugin for publishing moveit planning scene
  SENSORS.md
  gazebo_plugins/CMakeLists.txt
  gazebo_plugins/include/gazebo_plugins/gazebo_ros_moveit_planning_scene.h
  gazebo_plugins/package.xml
  gazebo_plugins/src/gazebo_ros_moveit_planning_scene.cpp
Labels: needs feedback

#1139 [Noetic] Added Ignition common profiler to gazebo_plugins
  gazebo_plugins/CMakeLists.txt
  gazebo_plugins/src/gazebo_ros_block_laser.cpp
  gazebo_plugins/src/gazebo_ros_bumper.cpp
  gazebo_plugins/src/gazebo_ros_camera.cpp
  gazebo_plugins/src/gazebo_ros_depth_camera.cpp
  gazebo_plugins/src/gazebo_ros_diff_drive.cpp
  gazebo_plugins/src/gazebo_ros_f3d.cpp
  gazebo_plugins/src/gazebo_ros_force.cpp
  gazebo_plugins/src/gazebo_ros_ft_sensor.cpp
  gazebo_plugins/src/gazebo_ros_gpu_laser.cpp
  gazebo_plugins/src/gazebo_ros_hand_of_god.cpp
  gazebo_plugins/src/gazebo_ros_harness.cpp
  gazebo_plugins/src/gazebo_ros_imu.cpp
  gazebo_plugins/src/gazebo_ros_imu_sensor.cpp
  gazebo_plugins/src/gazebo_ros_joint_pose_trajectory.cpp
  gazebo_plugins/src/gazebo_ros_joint_state_publisher.cpp
  gazebo_plugins/src/gazebo_ros_laser.cpp
  gazebo_plugins/src/gazebo_ros_multicamera.cpp
  gazebo_plugins/src/gazebo_ros_openni_kinect.cpp
  gazebo_plugins/src/gazebo_ros_p3d.cpp
  gazebo_plugins/src/gazebo_ros_planar_move.cpp
  gazebo_plugins/src/gazebo_ros_projector.cpp
  gazebo_plugins/src/gazebo_ros_prosilica.cpp
  gazebo_plugins/src/gazebo_ros_range.cpp
  gazebo_plugins/src/gazebo_ros_skid_steer_drive.cpp
  gazebo_plugins/src/gazebo_ros_tricycle_drive.cpp
  gazebo_plugins/src/gazebo_ros_triggered_camera.cpp
  gazebo_plugins/src/gazebo_ros_triggered_multicamera.cpp
  gazebo_plugins/src/gazebo_ros_vacuum_gripper.cpp
  gazebo_plugins/src/gazebo_ros_video.cpp
Labels: enhancement

#1140 Backport timeout argument to Dashing version of gazebo_ros
  gazebo_ros/scripts/spawn_entity.py
Labels: ros2
